### ISSUE TITLE
[PE-D][Tester C] Issue with adding multiple mods

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T13-0/tp#185]
![スクリーンショット 2023-11-03 午後4.16.03.png](https://raw.githubusercontent.com/sushiyade/ped/main/files/6e8462e0-9dfe-4065-8e10-d3f51bd1704f.png)

Unable to add mods which I have taken before in previous sems to current sems. How do I Input a Mod which I have retaken?

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: sushiyade/ped#1

**Comment by rocketninja7** [comment]
Specify in User Guide how to handle this case
