### ISSUE TITLE
[PE-D][Tester C] Mods restriction for preclusion

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T13-0/tp#187]
![スクリーンショット 2023-11-03 午後4.20.03.png](https://raw.githubusercontent.com/sushiyade/ped/main/files/c4c55f8e-6ec2-4c4f-bfad-e7e2f3674851.png)

Able to add Mods which are unable to be taken after taking certain mods i.e. preclusion mods

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: sushiyade/ped#2

**Comment by yyyaohhh** [comment]
Updated UserGuide in #223
