### ISSUE TITLE
[PE-D][Tester B] Add / Edit Features' grade and semester parameters are case-sensitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T13-0/tp#196]
I tried adding a module with everything in lowercase and discovered that the grade and semester parameters are case-sensitive as shown below:

For Grade:

![image.png](https://raw.githubusercontent.com/inezkok/ped/main/files/cb939923-5786-410e-95e7-08bfa16a1b68.png)

For Semester:

![image.png](https://raw.githubusercontent.com/inezkok/ped/main/files/29d282d2-63e2-41b1-b0a5-439d72045bc1.png)

Maybe you can change it to be case-insensitive since the casing doesn't really have an important meaning?

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: inezkok/ped#1

**Comment by yyyaohhh** [comment]
Updated UserGuide in #223
