### ISSUE TITLE
[PE-D][Tester B] Very few screenshots in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T13-0/tp#201]
When trying to follow along with the UG, I noticed that there were very few screenshots of the outcome of the commands? 

Maybe you can include screenshots of the outcomes for each feature (eg expected outcome/success messages and error messages) in the UG so users will have an easier time following along!

![image.png](https://raw.githubusercontent.com/inezkok/ped/main/files/c11dcd3b-bf5a-4799-ab92-0494729acb69.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: inezkok/ped#3

**Comment by yyyaohhh** [comment]
Fixed UserGuide in #223
