### ISSUE TITLE
[PE-D][Tester D] Outdated information 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T13-0/tp#217]
Module is now known as course and MC is now known as unit.

![image.png](https://raw.githubusercontent.com/tiongMax/ped/main/files/5ccfefe9-b46c-478c-9d28-570946272f33.png)

![image.png](https://raw.githubusercontent.com/tiongMax/ped/main/files/0beffe2c-a5b5-44e5-bfd7-b1278d6cc82b.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: tiongMax/ped#5

**Comment by yyyaohhh** [comment]
Fixed in #141
